export const createInitialAppState = (data) => ({
  language: "en",
  view: "dashboard",
  theme: "light",
  selectedConversationId: data.conversations[0]?.id,
  dateRange: { from: "", to: "" },
  agentOverrides: {},
  searchQuery: "",
  bookingDrill: {
    metricKey: "confirmedBookings",
    platformId: null,
    sourceId: null,
    contentId: null,
    agentId: null,
    bookingId: null,
    reportTab: "analysis",
    contextIds: null,
    contextLabel: null,
  },
});
